### PR TITLE
Pilot modes

### PR DESCRIPTION
**Pull request by lbajo**
Dear MROS team,

This pull request contains:
- Original names of the bt_xml files.
- New modes added.
- Topic name changed to match with modes.
- GUI updated.
- Minor changes in the license.

### CODE REVIEW

**Comment by fmrico** [comment]
LGTM. @jginesclavero, merge if you also agree.

**Comment by jginesclavero** [comment]
Good morning team! 
In https://github.com/MROS-RobMoSys-ITP/Pilot-URJC/pull/6 @fmrico talks about the modes and show this modes list: 
1. Normal.
2. Low_Battery
3. Obstructed
4. Lost
5. Network_Down

Must we keep these names in the pilot_modes.yaml? especially in ```pilot:``` section

**Comment by lbajo** [comment]
I changed the system modes names in pilot_modes.yaml to match with initial proposal names.

**Comment by jginesclavero** [comment]
LGTM! Merging

**Pull request merged**
